name: cace

# Events that trigger workflow
on:
  # Runs on all pushes to branches
  push:
  # Runs on all PRs
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

jobs:
  run-cace:
    runs-on: ubuntu-22.04
    name: Run CACE
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      # Run CACE on the design
      - name: Setup Environment and Run CACE
        uses: mole99/cace-action@main
        with:
          pdk_family: 'ihp-sg13g2'
          open_pdks_rev: '60361e2d3799fdc9de3d1b77f717cd008958f1a4'
          cace_root: '.'
          cace_datasheet: 'cace/sg13g2_leo_ip__ota5t.yaml'
          cace_source: 'rcx'
          token: ${{ secrets.GITHUB_TOKEN }}
      # Upload artifacts
      - name: Upload Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: runs
          path: |
            ${{ github.workspace }}/runs/
      # Add summary
      - name: Add Markdown to Step Summary
        if: success() || failure()
        run: cat runs/*/summary.md >> $GITHUB_STEP_SUMMARY
